channel1:
  dry_point: 27
  enabled: true
  warn_level: 0.2
  wet_point: 3
channel2:
  dry_point: 27
  enabled: true
  warn_level: 0.5
  wet_point: 3
channel3:
  dry_point: 27
  enabled: true
  warn_level: 0.4
  wet_point: 3
general:
  alarm_enable: true
  alarm_interval: 2
  light_level_low: 4.0
  black_screen_when_light_low: false
