channel1:
  dry_point: 27.5
  enabled: true
  warn_level: 0.4
  wet_point: 3.0
channel2:
  dry_point: 27.5
  enabled: true
  warn_level: 0.4
  wet_point: 3.0
channel3:
  dry_point: 27.5
  enabled: true
  warn_level: 0.4
  wet_point: 3.0
general:
  alarm_enable: true
  alarm_interval: 10.0
